CC = dmc
CFLAGS = -c -6 -o+all -mn -I../libjpeg/src -I../libpng/src

OBJS = src/image.obj

.c.obj:
	$(CC) $(CFLAGS) -o$@ $<

libimage: $(OBJS)
	lib -c -n lib/libimage.lib $(OBJS)

clean:
	erase /F /S *.obj
	erase /F lib\libimage.lib
